image: alpine/latest
packages:
  - rsync
  - hugo
sources:
  - https://git.sr.ht/~kota/recipes.nilsu.org
secrets:
  - 65dc7683-5d31-442a-b388-62b1d4452851
tasks:
  - build: |
      cd recipes.nilsu.org
      hugo --cleanDestinationDir
  - deploy: |
      cd recipes.nilsu.org
      sshopts="ssh -o StrictHostKeyChecking=no"
      rsync --rsh="$sshopts" -rdvP public/ kota@recipe.nilsu.org:/var/www/html/recipes.nilsu.org/
